UKHomeOffice/drt-lib

- src/main/scala/drt/auth/LoggedInUser.scala
- src/test/scala/drt/auth/LoggedInUserSpec.scala
- Adding Staff Movement Edit Role
> adding new Role StaffMovementsEdit

- .drone.yml
- project/Dependencies.scala
- src/main/scala/uk/gov/homeoffice/drt/auth/LoggedInUser.scala
- src/test/scala/uk/gov/homeoffice/drt/UrlsSpec.scala
- src/test/scala/uk/gov/homeoffice/drt/auth/LoggedInUserSpec.scala
> DRTII-635 Useful funcs for user with tests

- src/main/scala/uk/gov/homeoffice/drt/auth/Roles.scala
> DRTII-760 Add feature flag for Red List Feature

- project/Dependencies.scala
- src/main/scala/uk/gov/homeoffice/drt/auth/Roles.scala
- src/test/scala/uk/gov/homeoffice/drt/auth/RolesTest.scala
Create BHD role
Add BHD role to port roles list
Add regression test to prevent accidental updating of port roles
> DRTII-837 Create and add BHD to port roles. Add regression test

- src/main/scala/uk/gov/homeoffice/drt/auth/Roles.scala
> DRTII-831 adding nebo:upload role

- src/main/scala/uk/gov/homeoffice/drt/Nationality.scala
- src/main/scala/uk/gov/homeoffice/drt/redlist/RedListUpdateCommand.scala
- src/main/scala/uk/gov/homeoffice/drt/redlist/RedListUpdates.scala
Move RedList & Nationality classes into drt-lib to they can be used in multiple projects
> DRTII-803 Move RedList + Nationality classes into drt-lib

- .drone-v1.yml
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Bhd.scala
Fix incorrect role for BHD
Split build into 3 steps in attempt to make it run faster
> Drtii 910 fix bhd role

- src/main/scala/uk/gov/homeoffice/drt/auth/Roles.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/AirportConfigs.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Lba.scala
- src/test/scala/uk/gov/homeoffice/drt/auth/RolesTest.scala
> Drtii 480 lba port

- src/main/scala/uk/gov/homeoffice/drt/auth/Roles.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/AirportConfigs.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Dsa.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Huy.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Lba.scala
- src/test/scala/uk/gov/homeoffice/drt/auth/RolesTest.scala
Add DSA
Add HUY
Fix LBA splits - no egates
> Drtii 484 configure humberside

- src/main/scala/uk/gov/homeoffice/drt/auth/Roles.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/AirportConfigs.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Inv.scala
- src/test/scala/uk/gov/homeoffice/drt/auth/RolesTest.scala
> Drtii 533 inv

- src/main/scala/uk/gov/homeoffice/drt/ports/config/Bhx.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Edi.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Lgw.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Lhr.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Ltn.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Man.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Nqy.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Pik.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Sou.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Stn.scala
- update egate processing time mentioned in ticket [DRTII-932](https://collaboration.homeoffice.gov.uk/jira/browse/DRTII-932 )
> DRTII-932 update egate processing time

- src/main/scala/uk/gov/homeoffice/drt/auth/Roles.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/AirportConfigs.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Ext.scala
- src/test/scala/uk/gov/homeoffice/drt/auth/RolesTest.scala
> DRTII-560 adding exeter port config

- src/main/scala/uk/gov/homeoffice/drt/auth/Roles.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/AirportConfigs.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Mme.scala
- src/test/scala/uk/gov/homeoffice/drt/auth/RolesTest.scala
> DRTII-918 adding MME port

- src/main/scala/uk/gov/homeoffice/drt/ports/config/Bhx.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Edi.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Lgw.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Lhr.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Ltn.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Man.scala
- src/main/scala/uk/gov/homeoffice/drt/ports/config/Stn.scala
- updating terminal processing time
> DRTII-963 update terminal processing times

- src/main/scala/uk/gov/homeoffice/drt/ports/Terminals.scala
- src/test/scala/uk/gov/homeoffice/drt/ports/TerminalsTest.scala
Add "1" as a valid ACL terminal string
Test string to terminal
> DRTII-976 Add "1" to map to T1, and test for all mappings

- src/main/scala/uk/gov/homeoffice/drt/arrivals/Arrival.scala
- src/test/scala/uk/gov/homeoffice/drt/arrivals/ArrivalGenerator.scala
Replace simple `Long` with `Prediction` so we can keep an `updatedAt` value
> DRTII-975 Add Prediction to Arrival

- src/main/protobuf/Alert.proto
- src/main/protobuf/CrunchState.proto
- src/main/protobuf/DeskStatsMessage.proto
- src/main/protobuf/EgateBanksUpdates.proto
- src/main/protobuf/FixedPointMessage.proto
- src/main/protobuf/FlightsMessage.proto
- src/main/protobuf/FlightsSummary.proto
- src/main/protobuf/ModelAndFeatures.proto
- src/main/protobuf/NeboPassengersMessage.proto
- src/main/protobuf/PaxMessage.proto
- src/main/protobuf/Prediction.proto
- src/main/protobuf/RedListUpdates.proto
- src/main/protobuf/RegisteredArrivalMessage.proto
- src/main/protobuf/ShiftMessage.proto
- src/main/protobuf/StaffMovementMessages.proto
- src/main/protobuf/TerminalQueuesSummary.proto
- src/main/protobuf/Timestamp.proto
- src/main/protobuf/VoyageManifest.proto
Bring in protobuf schema files to avoid diverging versions in apps depending on the same messages
> DRTII-975 Add protobuf schema to avoid divergence between apps

- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/ApiArrivalsWithSplits.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/Arrival.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Edi.scala
Add update function to Arrival to retain fields we don't necessarily get in other feeds
Remove est chox column from EDI
> Drtii 1001 reimplement arrival hall logic for edi

- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Boh.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Ext.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Mme.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Nqy.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Pik.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Sou.scala
Fix config for single queue ports
> DRTII-1006 Fix port config for single queue ports

- proto/src/main/protobuf/FlightsMessage.proto
- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/ApiArrivalsWithSplits.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/Arrival.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/FeedSources.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/splits/ApiSplitsToSplitRatio.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ApiFlightWithSplitsSpec.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ArrivalSpec.scala
-  removing splitSource from TotalPaxSource in Arrival and using new HistoricApiFeedSource FeedSource.
> Drtii 797 refactor total pax

- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/Arrival.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ArrivalSpec.scala
- When TotalPax in arrival does not contain Feed Data then bestPcpPaxEstimate fallback to FeedSource in arrival
> Drtii 797 total pax fallback

- proto/src/main/protobuf/CrunchState.proto
Add terminal to `CrunchRequestMessage` to allow more fine grained calculations
> DRTII-1030 Add terminal to CrunchRequestMessage

- shared/src/main/scala/uk/gov/homeoffice/drt/ports/PaxTypeAndQueue.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/Queues.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/ports/PaxTypesAndQueuesTest.scala
Bring Cedat's export API columns in line with regular users
> Drtii 1023 add gbr and b5 jssk desk transaction times fix queue allocations

- shared/src/main/scala/uk/gov/homeoffice/drt/ports/PaxTypes.scala
Reinstate as we have some persisted data using this type
> DRTII-1043 Reinstate UndefinedPaxType

- shared/src/main/scala/uk/gov/homeoffice/drt/auth/Roles.scala
> Drtii 1044 add feature flag to force splits recalculation

- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/ArrivalsHeadings.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/auth/Roles.scala
adding rcc region based roles 
export arrival headings
> Drtii 1002

- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/ArrivalExportHeadings.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/ArrivalsHeadings.scala
Place all export header definitions in one place
- arrivalWithSplitsHeadings
- arrivalWithSplitsAndRawApiHeadings
- regionalExportHeadings
> Drtii 1159 region export columns are not up to date

- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/Arrival.scala
> Drtii 1148 arrival time

- .scala-steward.conf
- updating steward frequency to weekly 
- update dependency frequency to 30 days
> DRTII-1155 update steward frequency for PR and dependency PR

- .drone-v1.yml
- jvm/src/main/scala/uk/gov/homeoffice/drt/protobuf/serialisation/FlightMessageConversion.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/protobuf/serialisation/FlightMessageConversionSpec.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/ApiArrivalsWithSplits.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/Arrival.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/ForecastArrival.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/FeedSources.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ApiFlightWithSplitsSpec.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ArrivalGenerator.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ArrivalPcpPaxSpec.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ArrivalSpec.scala
Change `TotalPax` from `Set[TotalPaxSource]` to `Map[FeedSource, Option[Int]]`
> Drtii 1194 acl import causes pcp pax figure higher than total 2

- .drone-v1.yml
- build.sbt
- project/plugins.sbt
- sonar-project.properties
- Adding sonarqube properties and scoverages
> Drtii 1223 test coverage

- build.sbt
- jvm/src/test/scala/uk/gov/homeoffice/drt/actor/PredictionModelActorTest.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/arrivals/FlightsWithSplitsSpec.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/protobuf/serialisation/ModelAndFeaturesConversionTest.scala
- project/Dependencies.scala
- project/plugins.sbt
- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/ApiArrivalsWithSplits.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/Arrival.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/FlightsWithSplits.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/FlightsWithSplitsDiff.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/prediction/arrival/ArrivalFeatureValuesExtractor.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/prediction/arrival/ArrivalModelAndFeatures.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/splits/ApiSplitsToSplitRatio.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ApiFlightWithSplitsSpec.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ArrivalPcpPaxSpec.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ArrivalSpec.scala
Remove hard coded feed source order of of preference for best pax
> Drtii 1122 make pax feed source order configurable

- shared/src/main/scala/uk/gov/homeoffice/drt/ports/PaxTypes.scala
-  To keep previous age eligibility before date 2023-07-26
> DRTII-1272 update age eligibility for display age in flight charts

- shared/src/main/scala/uk/gov/homeoffice/drt/auth/Roles.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/Ports.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/auth/RolesTest.scala
> DRTII-1283 Remove DSA role

- shared/src/main/scala/uk/gov/homeoffice/drt/auth/Roles.scala
> Drtii 1305 alerting on incidents

- .drone-v1.yml
- build.sbt
- project/plugins.sbt
- project/protoc.sbt
- sonar-project.properties
Upgrade spark and other dependencies
Remove dead dependencies
Reorganise drone steps to run reliably with clearer naming
> Drtii 1343 upgrade spark library

- shared/src/main/scala/uk/gov/homeoffice/drt/ports/Queues.scala
Explicit type required in some use cases
> DRTII-1255 Add explicit type to queues

- shared/src/main/scala/uk/gov/homeoffice/drt/redlist/RedListUpdates.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/redlist/RedListUpdatesTest.scala
Hard code red list scrappage date so all dates after return an empty list
> DRTII-1354 Return empty red list when querying a date from 15/12/2023

- .drone-v1.yml
- shared/src/main/scala/uk/gov/homeoffice/drt/prediction/arrival/ArrivalModelAndFeatures.scala
- sonar-project.properties
Add school term & holiday dates for 2025, and change pre-summer period to scotland's summer holidays
> Drtii 1346 update peak dates and school times for 2024

- build.sbt
- jvm/src/main/scala/uk/gov/homeoffice/drt/jsonformats/LocalDateJsonFormat.scala
- jvm/src/main/scala/uk/gov/homeoffice/drt/jsonformats/PassengersSummaryFormat.scala
- jvm/src/main/scala/uk/gov/homeoffice/drt/models/PassengersSummary.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/jsonformats/LocalDateJsonFormatTest.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/jsonformats/PassengersSummaryFormatSpec.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/Queues.scala
Add passenger summaries classes & json serialisation
Add tests for serialisation & deserialisation
> Drtii 1411 adjust pax summaries end point

- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/Arrival.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/UpdatableTest.scala
Prevent max pax being overwritten by a None
> DRTII-1412 Do not lose max pax on update - add tests around update fn

- jvm/src/main/scala/uk/gov/homeoffice/drt/actor/PredictionModelActor.scala
- jvm/src/main/scala/uk/gov/homeoffice/drt/prediction/ActorModelPersistence.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/actor/PredictionModelActorTest.scala
Add point in time for prediction actor recovery
Remove dead code
> Drtii 1508 use appropriate model version in comparison end point

- jvm/src/main/scala/uk/gov/homeoffice/drt/actor/PredictionModelActor.scala
- jvm/src/main/scala/uk/gov/homeoffice/drt/actor/RecoveryLogging.scala
Don't replay events newer than point in time recovery request
> Drtii 1510 spike investigate late scheduled arrivals

- jvm/src/main/scala/uk/gov/homeoffice/drt/time/DateRange.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/time/DateRangeSpec.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/PortRegion.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/ports/PortRegionTest.scala
Move `DateRange` & tests from drt-v2
Ignore port code case in `PortRegion.fromPort`
> Drtii 1521 regional dashboard slow date ranges

- shared/src/main/scala/uk/gov/homeoffice/drt/Urls.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/UrlsSpec.scala
Update logout url for new keycloak version
> Drtii 1541 new users getting 404 when trying to access port

- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/ApiArrivalsWithSplits.scala
Add `hasLivePaxSource` function
> Drtii 1495 data quality indicators

- shared/src/main/scala/uk/gov/homeoffice/drt/ports/AirportConfig.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Abz.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Bfs.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Bhd.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Bhx.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Boh.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Brs.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Cwl.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Edi.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Ema.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Ext.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Gla.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Huy.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Inv.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Lba.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Lcy.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Lgw.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Lhr.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Lpl.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Ltn.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Man.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Mme.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Ncl.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Nqy.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Nwi.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Pik.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Sen.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Sou.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Stn.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/ports/config/AirportConfigsTest.scala
Add port names to `AirportConfig`
> Drtii 696 duplicated non descriptive page titles

- jvm/src/test/scala/uk/gov/homeoffice/drt/time/SDateSpec.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/time/SDateLike.scala
using single digit to display without zero
> Drtii 1681

- jvm/src/main/scala/uk/gov/homeoffice/drt/db/serialisers/FlightSerialiser.scala
- jvm/src/main/scala/uk/gov/homeoffice/drt/db/tables/FlightTable.scala
- jvm/src/test/resources/application.conf
Remove compression
Add new plain text columns to replace array byte json columns
> Drtii 1684 container restarts in kubernetes

- jvm/src/main/scala/uk/gov/homeoffice/drt/db/dao/FlightDao.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/actor/state/ArrivalsStateTest.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/arrivals/ArrivalGenerator.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/arrivals/CodeSharesTest.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/arrivals/FlightsWithSplitsDiffSpec.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/arrivals/FlightsWithSplitsSpec.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/prediction/arrival/ArrivalFeatureValuesExtractorSpec.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/prediction/arrival/HolidayLikeSpec.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/prediction/arrival/OneToManyFeatureColumnsTest.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/CodeShares.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ApiFlightWithSplitsSpec.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ArrivalGeneratorShared.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ArrivalPcpPaxSpec.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ArrivalSpec.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ArrivalsDiffSpec.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/SplitsForArrivalsSpec.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/UpdatableTest.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/splits/ApiSplitsToSplitRatioSpec.scala
Move CodeShare code from drt-v2 to enable codeshare filtering
Add unique flights dao function to eliminate code shares
> Drtii 1696 change api response to flat structure

- shared/src/main/scala/uk/gov/homeoffice/drt/ports/Terminals.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Sen.scala
Add SEN ACL terminal
Add ACL feed source to SEN config
> Drtii 1700 add acl to sen

- build.sbt
- jvm/src/main/scala/uk/gov/homeoffice/drt/actor/ConfigActor.scala
- jvm/src/main/scala/uk/gov/homeoffice/drt/db/dao/ABFeatureDao.scala
- jvm/src/main/scala/uk/gov/homeoffice/drt/db/dao/BorderCrossingDao.scala
- jvm/src/main/scala/uk/gov/homeoffice/drt/db/dao/UserFeedbackDao.scala
- jvm/src/main/scala/uk/gov/homeoffice/drt/db/serialisers/BorderCrossingSerialiser.scala
- jvm/src/main/scala/uk/gov/homeoffice/drt/db/tables/BorderCrossingTable.scala
- jvm/src/main/scala/uk/gov/homeoffice/drt/time/SDate.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/db/TestDatabase.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/db/dao/ABFeatureDaoTest.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/db/dao/BorderCrossingDaoTest.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/db/dao/CapacityHourlyDaoTest.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/db/dao/FlightDaoTest.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/db/dao/PassengersHourlyDaoTest.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/db/dao/QueueSlotDaoTest.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/db/dao/StatusDailyDaoTest.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/db/dao/UserFeedbackDaoTest.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/db/serialisers/BorderCrossingSerialiserTest.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/time/SDateLike.scala
Add border crossing
- table
- dao
- serialisation
- tests
> Drtii 1686 bx data upload

- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/AirportConfigDefaults.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Bhx.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Edi.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Lgw.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Lhr.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Ltn.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Man.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Stn.scala
Update desk transaction times for all ports
> DRTII-1667 Update desk transaction times for all ports

- jvm/src/main/scala/uk/gov/homeoffice/drt/jsonformats/PaxFiguresJsonFormat.scala
- jvm/src/main/scala/uk/gov/homeoffice/drt/models/PaxFigures.scala
Adding `PaxFigures` & `DayPaxFigures`
Adding json serialisation
> DRTII-1412 Add PaxFigures & json formats

- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/Arrival.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/arrivals/ArrivalSpec.scala
Add isDiverted
Test coverage for isCancelled & isDiverted
> Drtii 1755 diverted flights passengers are not filtered out

- jvm/src/main/scala/uk/gov/homeoffice/drt/protobuf/serialisation/FlightMessageConversion.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/arrivals/Arrival.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/prediction/arrival/ArrivalModelAndFeatures.scala
Rename lastChecked to lastUpdated
Only update `lastUpdated` if the prediction changes
> Drtii 1848 lhr failing health checks

- jvm/src/main/scala/uk/gov/homeoffice/drt/db/dao/EgateEligibilityDao.scala
- jvm/src/main/scala/uk/gov/homeoffice/drt/db/serialisers/EgateEligibilitySerialisation.scala
- jvm/src/main/scala/uk/gov/homeoffice/drt/db/tables/EgateEligibilityTable.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/db/dao/EgateEligibilityDaoTest.scala
- jvm/src/test/scala/uk/gov/homeoffice/drt/db/serialisers/EgateEligibilitySerialisationTest.scala
Add egate eligibility table to record daily eligible & underage passengers per terminal:
- table
- dao
- serialisation
- tests
> Drtii 1864 egate uptake historic simulation vs bx

- .drone-v1.yml
- build.sbt
- project/plugins.sbt
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/AirportConfigDefaults.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Bhx.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Edi.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Lgw.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Lhr.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Ltn.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Man.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Stn.scala
DRTII-1893 - Update pax transaction times Q1 25-26
> DRTII-1893 Updated desk transaction times

- README.md
- jvm/src/test/scala/uk/gov/homeoffice/drt/models/UserPreferencesTest.scala
- shared/src/main/scala/uk/gov/homeoffice/drt/models/UserPreferences.scala
- adding none terminal when no terminals are selected as we want default all terminal to selected when user are viewing dashboard without any selection
> Drtii 1890 dashboard error

- shared/src/main/scala/uk/gov/homeoffice/drt/ports/config/Lhr.scala
- shared/src/test/scala/uk/gov/homeoffice/drt/ports/AirportConfigSpec.scala
T2: 29 desks
T5: 27 desks
Remove fast track queue for LHR
Set min 2 egate banks 06:00 - 23:00 T2, T3 & T5 - T4 has only 1 bank
> Drtii 1896 config changes lhr
